###
GET http://localhost:8000/health

### Knowledge
GET http://localhost:8000/knowledge/status

### Knowledge
GET http://localhost:8000/knowledge/reload

###
POST http://localhost:8000/chat

{
    "messages": [
      {
        "role": "user",
        "content": "Tell me the models defined for the API"
      }
    ]
  
}

### With history
POST http://localhost:8000/chat

{
    "messages": [
      {
        "role": "assistant",
        "content": "You can use API chat method to chat with the API"
      },
      {
        "role": "user",
        "content": "How van chat with the project?"
      }
    ]
  
}

### Improve
POST http://localhost:8000/improve

{
    "messages": [
      {
        "role": "user",
        "content": "Create a models folder for the API module and split models.py into multiples files, update imports"
      }
    ]
  
}